"""db migration

Revision ID: fb9c466e539c
Revises: 0002_answer_feedback
Create Date: 2026-05-13 11:00:31.426207

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fb9c466e539c'
down_revision: str | Sequence[str] | None = '0002_answer_feedback'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column('answer_feedback', 'domain',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Enum('TECHNICAL_DOCUMENT', 'RESEARCH_PAPER', 'LEGAL_CONTRACT', 'HEALTHCARE_DOCUMENT', 'FINANCIAL_DOCUMENT', name='corpus_domain', native_enum=False),
               existing_nullable=True)
    # These indexes are created by the legacy startup migrations; on a fresh DB
    # they may not exist, so we drop them conditionally.
    op.execute("DROP INDEX IF EXISTS idx_answer_feedback_created_at")
    op.execute("DROP INDEX IF EXISTS idx_answer_feedback_domain_rating")
    op.execute("DROP INDEX IF EXISTS idx_document_chunks_document_chunk")
    op.execute("DROP INDEX IF EXISTS idx_document_chunks_fts")
    op.execute("DROP INDEX IF EXISTS idx_documents_checksum_unique")
    op.execute("DROP INDEX IF EXISTS idx_documents_domain_created_at")
    op.execute("DROP INDEX IF EXISTS idx_query_traces_created_at")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_query_traces_created_at'), 'query_traces', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_documents_domain_created_at'), 'documents', ['domain', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_documents_checksum_unique'), 'documents', ['checksum'], unique=True)
    op.create_index(op.f('idx_document_chunks_fts'), 'document_chunks', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_document_chunks_document_chunk'), 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('idx_answer_feedback_domain_rating'), 'answer_feedback', ['domain', 'rating'], unique=False)
    op.create_index(op.f('idx_answer_feedback_created_at'), 'answer_feedback', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('answer_feedback', 'domain',
               existing_type=sa.Enum('TECHNICAL_DOCUMENT', 'RESEARCH_PAPER', 'LEGAL_CONTRACT', 'HEALTHCARE_DOCUMENT', 'FINANCIAL_DOCUMENT', name='corpus_domain', native_enum=False),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
